//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SchoolSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SchoolSystemEntites : DbContext
    {
        public SchoolSystemEntites()
            : base("name=SchoolSystemEntites")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Digree> Digrees { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Experiecne> Experiecnes { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<Province> Provinces { get; set; }
        public virtual DbSet<Qualification> Qualifications { get; set; }
        public virtual DbSet<School> Schools { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
    }
}
