//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SchoolSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Qualification
    {
        public int QualificationId { get; set; }
        public string QualificationName { get; set; }
        public Nullable<System.DateTime> PassingDate { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<System.DateTime> ModifiedDateTime { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> SchoolId { get; set; }
        public int EmployeeId { get; set; }
        public int DigreeId { get; set; }
    
        public virtual Digree Digree { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
