//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SchoolSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblSchool
    {
        public int SchoolId { get; set; }
        public string SchoolName { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> ProvinceId { get; set; }
        public string Address { get; set; }
        public string RegistrationNo { get; set; }
        public string NTNNo { get; set; }
        public string PtclNo { get; set; }
        public string CellNo { get; set; }
        public string CellNo1 { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public string SROfficerName { get; set; }
        public string SROffiersContactNo { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ModifiedBY { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<System.DateTime> ModifeidDateTime { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public int PackageId { get; set; }
        public byte[] SchoolLogo { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public string AdminUserName { get; set; }
    }
}
