//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SchoolSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblSchoolPackage
    {
        public int PackageID { get; set; }
        public string PackageName { get; set; }
        public Nullable<double> Price { get; set; }
        public string Feature { get; set; }
    }
}
